# -------------------------------- GENERATED BY C_BUILD --------------------------------
import os
import sys

def FIND_C_BUILD(current_dir):
    if os.path.isdir(os.path.join(current_dir, "c_build")):
        sys.path.insert(0, current_dir)
        return

    parent_dir = os.path.dirname(current_dir)
    if parent_dir != current_dir:
        FIND_C_BUILD(parent_dir)

FIND_C_BUILD(os.path.abspath(os.path.dirname(__file__)))
from c_build.source.UserUtilities import *
from c_build.source.Manager import *
# --------------------------------------------------------------------------------------s

cc: CompilerConfig = CompilerConfig(
    compiler_name = C_BUILD_COMPILER_NAME() if C_BUILD_IS_DEPENDENCY() else "INVALID_COMPILER",
)

pc: ProjectConfig = ProjectConfig(
    project_name = "SFE_Test_Scenes",
    project_dependencies = [
        Dependency(
            name = "SFE"
        ),
    ],
    project_debug_with_visual_studio = False,
    project_rebuild_project_dependencies = True,
    project_executable_names = ["particle.exe"]
)

if IS_WINDOWS() and not C_BUILD_IS_DEPENDENCY():
    cc.compiler_name = "cl"
elif IS_DARWIN() and not C_BUILD_IS_DEPENDENCY():
    cc.compiler_name = "clang"
elif IS_LINUX() and not C_BUILD_IS_DEPENDENCY():
    cc.compiler_name = "gcc"

if cc.compiler_name == "cl":
    cc.compiler_warning_level = "4"
    cc.compiler_disable_specific_warnings = [
        "4244", "4100", "4458", 
        "4201", "4116", "4702",
        "4996"
    ]
else:
    cc.compiler_warning_level = ""
    cc.compiler_disable_specific_warnings = [
        "deprecated", 
        "parentheses", 
        "implicit-fallthrough",
        "unused-variable"
    ]

build_postfix = f"./build_{cc.compiler_name}/{C_BUILD_BUILD_TYPE()}"

inject = []
libs = [
    f"../../SFE/{build_postfix}/sfe.lib",
]

if IS_WINDOWS():
    if cc.compiler_name == "cl":
        glfw_path = "../../SFE/Vendor/glfw/bin/windows/lib-static-ucrt/glfw3dll.lib"  
    else: 
        glfw_path = "../../SFE/Vendor/glfw/bin/windows/lib-mingw-w64/libglfw3dll.a"
        inject += ["-L/ucrt64/lib", "-lassimp"] #hacky but works for now
    
    libs += [
        glfw_path,
        f"../../SFE/Vendor/assimp/bin/windows/assimp-vc143-mtd.lib",
        GET_LIB_FLAG(cc, "Kernel32"),
        GET_LIB_FLAG(cc, "User32"),
        GET_LIB_FLAG(cc, "Gdi32"),
        GET_LIB_FLAG(cc, "OpenGL32"), 
        GET_LIB_FLAG(cc, "Winmm"),
    ]
elif IS_DARWIN():
    inject += ["-Wl,-rpath,@executable_path"]
    libs += [
        f"../../SFE/Vendor/glfw/bin/macos/lib-arm64/libglfw3.a",
        f"../../SFE/Vendor/assimp/bin/macos/libassimp.dylib",
        "-framework OpenGL",
        "-framework Cocoa",
        "-framework IOKit",
        "-framework CoreFoundation",
    ]
    
include_paths =  [
    "../..",
    "../../SFE",

    "../../SFE/Vendor",
    "../../SFE/Vendor/stb",
    "../../SFE/Vendor/glad/include", 
    "../../SFE/Vendor/glfw",
    "../../SFE/Vendor/assimp/include",
]

procedures_config = {
    "terrain_scene": ProcedureConfig(
        build_directory = f"./{build_postfix}",
        output_name = f"terrain_scene.exe",
        source_files = [
            "../../Scenes/TerrainScene/main.cpp",
            "../../Scenes/TerrainScene/Shaders/**/*.cpp",
        ],
        additional_libs = libs,
        include_paths = include_paths,
        compiler_inject_into_args=inject
    ),
    
    "particle scene": ProcedureConfig(
        build_directory = f"./{build_postfix}",
        output_name = f"particle.exe",
        source_files = [
            "../../Scenes/ParticleScene/main.cpp",
            "../../Scenes/ParticleScene/Shaders/**/*.cpp",
        ],
        additional_libs = libs,
        include_paths = include_paths,
        compiler_inject_into_args=inject
    ),
    
    "text scene": ProcedureConfig(
        build_directory = f"./{build_postfix}",
        output_name = f"text.exe",
        source_files = [
            "../../Scenes/TextScene/main.cpp",
            "../../Scenes/TextScene/Shaders/**/*.cpp",
        ],
        additional_libs = libs,
        include_paths = include_paths,
        compiler_inject_into_args=inject
    )
}

manager: Manager = Manager(cc, pc, procedures_config)
manager.build_project()
# ------------------------------------------------------------------------------------

if IS_WINDOWS():
    if cc.compiler_name == "cl":
        COPY_FILE_TO_DIR("./SFE/Vendor/glfw/bin/windows/lib-static-ucrt", "glfw3.dll", build_postfix)
    else:
        COPY_FILE_TO_DIR("./SFE/Vendor/glfw/bin/windows/lib-mingw-w64", "glfw3.dll", build_postfix)
            
    COPY_FILE_TO_DIR("./SFE/Vendor/assimp/bin/windows", "assimp-vc143-mtd.dll", build_postfix)
elif IS_DARWIN():
    COPY_FILE_TO_DIR("./SFE/Vendor/assimp/bin/macos", "libassimp.6.dylib", build_postfix)